#! /bin/sh

rm -rf /tmp/booth
mkdir  /tmp/booth

node test/socket.test && \
node test/unix.test   && \
node test/room.test   && \
node test/error.test  && \
node test/buffer.test && \
node test/once-when-request.test
