#! /bin/sh
#
# process.versions.deno, process.versions.node
# process.execPath
# import.meta.url
#

Deno ()
{
	deno run \
		-R=. \
		-R=/tmp/booth \
		-R=$(which deno) \
		-W=/tmp/booth/ \
		-N=0.0.0.0,127.0.0.1 \
		-E \
		"${@}"
}

set -e


Pkill ()
{
	pkill -f '\-\-residual' || true
}


rm -rf /tmp/booth
mkdir  /tmp/booth


if false
then
	Pkill
	tsx test/residual.test.ts
	# Deno test/residual.test.ts
	exit
fi


tsx test/socket.test.ts
tsx test/unix.test.ts
tsx test/room.test.ts
tsx test/error.test.ts
tsx test/buffer.test.ts
tsx test/once-when-request.test.ts
tsx test/stdio.test.ts
tsx test/recv.test.ts
node test/postmessage.test.js
Pkill
tsx test/residual.test.ts


rm -rf /tmp/booth
mkdir  /tmp/booth


Deno ./test/socket.test.ts
# Deno test/unix.test.ts # (see https://github.com/denoland/deno/issues/27450)
Deno test/room.test.ts
Deno test/error.test.ts
Deno test/buffer.test.ts
Deno test/once-when-request.test.ts
Deno --allow-run test/stdio.test.ts
Deno test/recv.test.ts
Deno test/postmessage.test.js
# Pkill
# Deno test/residual.test.ts
