#! /bin/sh
#
# process.versions.deno, process.versions.node
# process.execPath
# import.meta.url
#


set -e


Deno ()
{
	deno run \
		-R=. \
		-R=/tmp/booth \
		-R=$(which deno) \
		-W=/tmp/booth/ \
		-N=0.0.0.0,127.0.0.1 \
		-E \
		"${@}"
}

Clean ()
{
	rm -rf /tmp/booth
	mkdir  /tmp/booth
}

Pkill ()
{
	pkill -9 -f '\-\-residual' || true

	while nc -z localhost 9009; do sleep .5; done
	sleep 3
}


Pkill
Clean


if false
then
	Pkill
	tsx test/residual.test.ts

	if true
	then
		Pkill
		Deno --allow-run test/residual.test.ts
	fi

	Pkill
	exit
fi


tsx --version
echo ''

tsx test/socket.test.ts
tsx test/unix.test.ts
tsx test/room.test.ts
tsx test/error.test.ts
tsx test/buffer.test.ts
tsx test/once-when-request.test.ts
tsx test/stdio.test.ts
tsx test/recv.test.ts
node test/postmessage.test.js
tsx test/residual.test.ts


Pkill
Clean


echo ''
deno --version
echo ''

Deno ./test/socket.test.ts
# Deno test/unix.test.ts # (see https://github.com/denoland/deno/issues/27450)
Deno test/room.test.ts
Deno test/error.test.ts
Deno test/buffer.test.ts
Deno test/once-when-request.test.ts
Deno --allow-run test/stdio.test.ts
Deno test/recv.test.ts
Deno test/postmessage.test.js
Deno --allow-run test/residual.test.ts

Pkill
